var partyConfig = {
  "parties": [{
    "name": "VVD",
    "short": "VVD",
    "slug": "vvd",
    "link": "http:\/\/vvd.nl",
    "logo": "logos\/vvd.svg",
  }, {
    "name": "PvdA",
    "short": "PvdA",
    "slug": "pvda",
    "link": "https:\/\/www.pvda.nl\/verkiezingen\/verkiezingsprogramma\/",
    "activated": true,
    "preselected": false,
    "logo": "logos\/pvda.svg",
  }, {
    "name": "PVV",
    "short": "PVV",
    "slug": "pvv",
    "link": "http:\/\/pvv.nl\/",
    "activated": true,
    "preselected": false,
    "logo": "logos\/pvv.svg",
  }, {
    "name": "SP",
    "short": "SP",
    "slug": "sp",
    "link": "https:\/\/www.sp.nl\/",
    "activated": true,
    "preselected": false,
    "logo": "logos\/sp.svg",
  }, {
    "name": "CDA",
    "short": "CDA",
    "slug": "cda",
    "link": "https:\/\/www.cda.nl\/",
    "activated": true,
    "preselected": false,
    "logo": "logos\/cda.svg",
  }, {
    "name": "D66",
    "short": "D66",
    "slug": "d66",
    "link": "http:\/\/d66.nl",
    "activated": true,
    "preselected": false,
    "logo": "logos\/d66.svg",
  }, {
    "name": "ChristenUnie",
    "short": "ChristenUnie",
    "slug": "christenunie",
    "link": "https:\/\/www.christenunie.nl\/",
    "activated": true,
    "preselected": false,
    "logo": "logos\/christenunie.svg",
  }, {
    "name": "GroenLinks",
    "short": "GroenLinks",
    "slug": "groenlinks",
    "link": "https:\/\/groenlinks.nl\/",
    "activated": true,
    "preselected": false,
    "logo": "logos\/groenlinks.svg",
  }, {
    "name": "SGP",
    "short": "SGP",
    "slug": "sgp",
    "link": "https:\/\/www.sgp.nl\/",
    "activated": true,
    "preselected": false,
    "logo": "logos\/sgp.svg",
  }, {
    "name": "Partij voor de Dieren",
    "short": "Partij voor de Dieren",
    "slug": "partij-voor-de-dieren",
    "link": "https:\/\/www.partijvoordedieren.nl\/",
    "activated": true,
    "preselected": false,
    "logo": "logos\/pvdd.svg",
  }, {
    "name": "50Plus",
    "short": "50Plus",
    "slug": "50plus",
    "link": "http:\/\/50pluspartij.nl\/",
    "activated": true,
    "preselected": false,
    "logo": "logos\/50plus.svg",
  }, {
    "name": "OndernemersPartij",
    "short": "OndernemersPartij",
    "slug": "ondernemerspartij",
    "link": "http:\/\/www.ondernemerspartij.nl",
    "activated": true,
    "preselected": false,
    "logo": "logos\/ondernemerspartij.png",
  }, {
    "name": "VNL",
    "short": "VNL",
    "slug": "vnl",
    "link": "http:\/\/vnl.nu",
    "activated": true,
    "preselected": false,
    "logo": "logos\/vnl.svg",
  }, {
    "name": "DENK",
    "short": "DENK",
    "slug": "denk",
    "link": "https:\/\/www.bewegingdenk.nl\/",
    "activated": true,
    "preselected": false,
    "logo": "logos\/denk.svg",
  }, {
    "name": "Nieuwe Wegen",
    "short": "Nieuwe Wegen",
    "slug": "nieuwe-wegen",
    "link": "http:\/\/nieuwewegen.nu",
    "activated": true,
    "preselected": false,
    "logo": "logos\/nieuwewegen.png",
  }, {
    "name": "Forum voor Democratie",
    "short": "Forum voor Democratie",
    "slug": "forum-voor-democratie",
    "link": "https:\/\/forumvoordemocratie.nl\/",
    "activated": true,
    "preselected": false,
    "logo": "logos\/forumvoordemocratie.png",
  }, {
    "name": "De Burger Beweging",
    "short": "De Burger Beweging",
    "slug": "de-burger-beweging",
    "link": "http:\/\/www.deburgerbeweging.nl\/",
    "activated": true,
    "preselected": false,
    "logo": "logos\/burgerbeweging (2).png",
  }, {
    "name": "Vrijzinnige Partij",
    "short": "Vrijzinnige Partij",
    "slug": "vrijzinnige-partij",
    "link": "http:\/\/www.vrijzinnigepartij.nl",
    "activated": true,
    "preselected": false,
    "logo": "logos\/vrijzinnigepartij.png",
  }, {
    "name": "Piratenpartij",
    "short": "Piratenpartij",
    "slug": "piratenpartij",
    "link": "https:\/\/piratenpartij.nl\/",
    "activated": true,
    "preselected": false,
    "logo": "logos\/piratenpartij.svg",
  }, {
    "name": "Artikel 1",
    "short": "Artikel 1",
    "slug": "artikel-1",
    "link": "http:\/\/www.artikel1.org",
    "activated": true,
    "preselected": false,
    "logo": "logos\/artikel1.png",
  }, {
    "name": "Niet Stemmers",
    "short": "Niet Stemmers",
    "slug": "niet-stemmers",
    "link": "http:\/\/www.nietstemmers.nl",
    "activated": true,
    "preselected": false,
    "logo": "logos\/nietstemmers.svg",
  }, {
    "name": "Libertarische Partij",
    "short": "Libertarische Partij",
    "slug": "libertarische-partij",
    "link": "http:\/\/www.stemlp.nl",
    "activated": true,
    "preselected": false,
    "logo": "logos\/libertarischepartij.svg",
  }, {
    "name": "Lokaal in de Kamer",
    "short": "Lokaal in de Kamer",
    "slug": "lokaal-in-de-kamer",
    "link": "http:\/\/lokaalindekamer.nl",
    "activated": true,
    "preselected": false,
    "logo": "logos\/lokaalindekamer.svg",
  }]
};